const LANGNAMES = {
    bxr: {
        eng: "Buryat",
        nob: "Burjatisk",
        sme: "Burjátagiella",
        fin: "Burjaatin kieli",
        rus: "Бурятский язык",
    },
    ciw: {
        eng: "Chippewa",
        nob: "Ojibwe",
        sme: "Ojibwegiella",
        fin: "Ojibwen kieli",
        rus: "Чиппева",
    },
    chp: {
        eng: "Denesuline",
        nob: "Dene suline",
        sme: "Denesuline",
        fin: "Denesuline",
        rus: "Дене Сулин",
    },
    chr: {
        eng: "Cherokee",
        nob: "Cherokesisk",
        sme: "Cherokee",
        fin: "Cherokeen kieli",
        rus: "Чероки",
    },
    cor: {
        eng: "Cornish",
        nob: "Kornisk",
        sme: "Kornagiella",
        fin: "Korni",
        rus: "Корнский язык",
    },
    deu: {
        eng: "German",
        nob: "Tysk",
        sme: "Duiskkagiella",
        fin: "Saksa",
        rus: "Немецкий язык",
    },
    eng: {
        eng: "English",
        nob: "Engelsk",
        sme: "Eaŋgalsgiella",
        fin: "Englanti",
        rus: "Англиийский язык",
    },
    evn: {
        eng: "Evenki",
        nob: "Evenkisk",
        sme: "Evenkigiella",
        fin: "Evenkin kieli",
        rus: "Эвенкийский язык",
    },
    est: {
        eng: "Estonian",
        nob: "Estisk",
        sme: "Esttegiella",
        fin: "Viro",
        rus: "Эстонский язык",
    },
    fao: {
        eng: "Faroese",
        nob: "Færøysk",
        sme: "Fearagiella",
        fin: "Fäärin kieli",
        rus: "Фарерский язык",
    },
    fin: {
        eng: "Finnish",
        nob: "Finsk",
        sme: "Suomagiella",
        fin: "Suomi",
        rus: "финский язык",
    },
    fit: {
        eng: "Meänkieli",
        nob: "Meänkieli",
        sme: "Meängiella",
        fin: "Meänkieli",
        rus: "Меянкиели",
    },
    gle: {
        eng: "Irish",
        nob: "Irsk",
        sme: "Iirragiella",
        fin: "Iiri",
        rus: "Ирландский язык",
    },
    fkv: {
        eng: "Kven",
        nob: "Kvensk",
        sme: "Kveanagiella",
        fin: "Kveeni",
        rus: "Квенский язык",
    },
    hdn: {
        eng: "Northern Haida",
        nob: "Nordhaida",
        sme: "Davvihaidagiella",
        fin: "Pohjoishaida",
        rus: "северохайдский язык",
    },
    hun: {
        eng: "Hungarian",
        nob: "Ungarsk",
        sme: "Ungáragiella",
        fin: "Unkari",
        rus: "Венгерский язык",
    },
    izh: {
        eng: "Ingrian",
        nob: "Ingrisk",
        sme: "Inkeroisgiella",
        fin: "Inkeroinen",
        rus: " язык",
    },
    koi: {
        eng: "Komi Permyak",
        nob: "Komipermjakisk",
        sme: "Komipermjakgiella",
        fin: "Komipermjakki",
        rus: " язык",
    },
    kom: {
        eng: "Komi",
        nob: "Komi",
        sme: "Komigiella",
        fin: "Komi",
        rus: "Венгерский язык",
    },
    kpv: {
        eng: "Komi",
        nob: "Syrjensk",
        sme: "Komigiella",
        fin: "Komi",
        rus: "Коми язык",
    },
    ipk: {
        eng: "Iñupiaq",
        nob: "Inupiak",
        sme: "Inupiaka",
        fin: "Inupiatun",
        rus: "инупиакский язык",
    },
    kal: {
        eng: "Greenlandic",
        nob: "Grønlandsk",
        sme: "Ruonáeatnanlaš",
        fin: "Grönlannin kieli",
        rus: "Гренландский язык",
    },
    kca: {
        eng: "Khanty",
        nob: "Khanti",
        sme: "Hantigiella",
        fin: "Hantin kieli",
        rus: "Хантыйский язык",
    },
    lav: {
        eng: "Latvian",
        nob: "Latvisk",
        sme: "Latviagiella",
        fin: "Latvia",
        rus: "Латвийский язык",
    },
    liv: {
        eng: "Livonian",
        nob: "Livisk",
        sme: "Liivigiella",
        fin: "Liivin kieli",
        rus: "Ливский язык",
    },
    mdf: {
        eng: "Moksha",
        nob: "Moksja",
        sme: "Mokšagiella",
        fin: "Mokša",
        rus: "Мокшанский язык",
    },
    mhr: {
        eng: "Eastern Mari",
        nob: "Østmarisk",
        sme: "Niitomarigiella",
        fin: "Niitymari",
        rus: "Луговомарийский язык",
    },
    mns: {
        eng: "Mansi",
        nob: "Mansisk",
        sme: "Mansigiella",
        fin: "Mansi",
        rus: "Мансийский язык",
    },
    mrj: {
        eng: "Hill Mari",
        nob: "Vestmarisk",
        sme: "Várremarigiella",
        fin: "Vuorimari",
        rus: "Горномарийский язык",
    },
    myv: {
        eng: "Erzya",
        nob: "Erzja",
        sme: "Ersagiella",
        fin: "Ersä",
        rus: "Эрзянский язык",
    },
    nio: {
        eng: "Nganasan",
        nob: "Nganasansk",
        sme: "Nganasanagiella",
        fin: "Nganasanin kieli",
        rus: "Нганасанский язык",
    },
    nob: {
        eng: "Norwegian bokmål",
        nob: "Norsk bokmål",
        sme: "Dárogiella",
        fin: "Norja",
        rus: "Норвежский язык",
    },
    olo: {
        eng: "Livvi-Karelian",
        nob: "Livvisk",
        sme: "Livvi",
        fin: "Livvi",
        rus: "Ливвиковский язык",
    },
    otw: {
        eng: "Odawa",
        nob: "Odawa",
        sme: "Odawa",
        fin: "Odawa",
        rus: "Оттава",
    },
    ron: {
        eng: "Romanian",
        nob: "Rumensk",
        sme: "Romaniagiella",
        fin: "Romania",
        rus: "Румынский язык",
    },
    rmf: {
        eng: "Finnish Kalo",
        nob: "Kalo finsk romani",
        sme: "Suoma romanigiella",
        fin: "Suomen romanikieli",
        rus: "Финский кало",
    },
    rus: {
        eng: "Russian",
        nob: "Russisk",
        sme: "Ruoššagiella",
        fin: "Venäjä",
        rus: "Русский язык",
    },
    sjd: {
        eng: "Kildin Sámi",
        nob: "Kildinsamisk",
        sme: "Gielddasámegiella",
        fin: "Kiltinänsaame",
        rus: "Кильдинский язык",
    },
    sje: {
        eng: "Pite Sámi",
        nob: "Pitesamisk",
        sme: "Bihtánsámegiella",
        fin: "Piitimensaame",
        rus: "Пите саамский язык",
    },
    sjt: {
        eng: "Ter Sámi",
        nob: "Tersamisk",
        sme: "Darjjesámegiella",
        fin: "Turjansaame",
        rus: "Йоканьгско-саамский язык",
    },
    sma: {
        eng: "South Sámi",
        nob: "Sørsamisk",
        sme: "Lullisámegiella",
        fin: "Eteläsaame",
        rus: "Южносаамский язык",
    },
    sme: {
        eng: "North Sámi",
        nob: "Nordsamisk",
        sme: "Davvisámegiella",
        fin: "Pohjoissaame",
        rus: "Северосаамский язык",
    },
    smj: {
        eng: "Lule Sámi",
        nob: "Lulesamisk",
        sme: "Julevsámegiella",
        fin: "Luulajansaame",
        rus: "Люлесаамский язык",
    },
    smn: {
        eng: "Inari Sámi",
        nob: "Enaresamisk",
        sme: "Anárašgiella",
        fin: "Inarinsaame",
        rus: "Инарисаамский язык",
    },
    sms: {
        eng: "Skolt Sámi",
        nob: "Skoltesamisk",
        sme: "Nuortalašgiella",
        fin: "Koltansaame",
        rus: "Колтта-саамский язык",
    },
    som: {
        eng: "Somali",
        nob: "Somalisk",
        sme: "Somaligiella",
        fin: "Somali",
        rus: "Сомалийский язык",
    },
    srs: {
        eng: "Tsuutʼina",
        nob: "Tsuutʼina",
        sme: "Tsuutʼina",
        fin: "Tsuut’ina",
        rus: "Тсу т'ина",
    },
    swe: {
        eng: "Swedish",
        nob: "Svensk",
        sme: "Ruoŧagiella",
        fin: "Ruotsi",
        rus: "Шведсйий язык",
    },
    tkl: {
        eng: "Tokelau",
        nob: "Tokelauisk",
        sme: "Tokelaugiella",
        fin: "Tokelaun kieli",
        rus: "Токелау",
    },
    udm: {
        eng: "Udmurt",
        nob: "Udmurtisk",
        sme: "Udmurtagiella",
        fin: "Udmurtti",
        rus: "удмуртский язык",
    },
    vep: {
        eng: "Veps",
        nob: "Vepsisk",
        sme: "Vepsägiella",
        fin: "Vepsän kieli",
        rus: "Вепсский язык",
    },
    vot: {
        eng: "Votic",
        nob: "Votisk",
        sme: "Vatjagiella",
        fin: "Vatja",
        rus: "Водский язык",
    },
    vro: {
        eng: "Võro",
        nob: "Võro",
        sme: "Võrogiella",
        fin: "Võro",
        rus: "Выруский язык",
    },
    yrk: {
        eng: "Nenets",
        nob: "Nenetsisk",
        sme: "Nenetsagiella",
        fin: "Nenetsi",
        rus: "Ненецкий язык",
    },
};

type OfLang = keyof typeof LANGNAMES;
type InLang = "eng" | "nob" | "sme" | "fin" | "rus";

export function langname(of: OfLang, in_: InLang): string {
    return LANGNAMES[of][in_].replace(/ /g, "\u{A0}");
}

export function iso6393_from_6391(code: string): string {
    switch (code) {
        case "en": return "eng";
        case "nb": return "nob";
        case "se": return "sme";
        case "fi": return "fin";
        case "ru": return "rus";
        default: throw Error(`unknown iso6391 code: ${code}`);
    }
}

